Close the file channel created for a non-readonly StreamsLayout so the file can be deleted
reaktivity/k3po-nukleus-ext.java pull request #3
Opened 2017-05-08 17:08 UTC by cmebarrow

on Windows.

2017-05-08 17:28 UTC, jfallows requested changes

2017-05-08 17:28 UTC, jfallows commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +        RingBuffer throttleBuffer, FileChannel fileChannel)
This should really be picked up by checkstyle, please move argument to next line.

2017-05-08 17:28 UTC, jfallows commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +    private final FileChannel fileChannel;
Would it be worth treating this as `Closeable cleanup;` instead?

2017-05-08 18:38 UTC, cmebarrow commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +        RingBuffer throttleBuffer, FileChannel fileChannel)
done

2017-05-08 18:38 UTC, cmebarrow commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +    private final FileChannel fileChannel;
done

2017-05-08 20:09 UTC, jfallows requested changes

2017-05-08 20:09 UTC, jfallows commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +            CloseHelper.close(fileChannel);
Let's move this `CloseHelper.close(...)` call up above the `AtomicBuffer` declarations, tighter to the relevant scope.

2017-05-08 20:09 UTC, jfallows commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +            FileChannel fileChannel = null;
Suggest changing the declared type to `Closeable`.

2017-05-08 20:09 UTC, jfallows commented on src/test/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayoutTest.java
> +        File streams = new File(fileName);
Recommend using forward slashes only for portable filenames in Java, even on Windows.
http://www.moreofless.co.uk/portable-filenames-java/

2017-05-08 20:09 UTC, jfallows commented on src/test/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayoutTest.java
> +        IoUtil.delete(streams, false);
Consider using `Paths.get(...)` and `Files.delete(...)` instead of `new File(...)` and `IoUtil.delete(...)`.

2017-05-08 21:43 UTC, cmebarrow commented on src/test/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayoutTest.java
> +        File streams = new File(fileName);
done

2017-05-08 21:45 UTC, cmebarrow commented on src/test/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayoutTest.java
> +        IoUtil.delete(streams, false);
done

2017-05-08 23:10 UTC, jfallows requested changes

2017-05-08 23:10 UTC, jfallows commented on src/test/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayoutTest.java
> +        assertTrue(streams.toFile().exists());
Use `Files.exists(streams)` instead of `streams.toFile().exists()`.

2017-05-09 17:08 UTC, jfallows commented on src/main/java/org/reaktivity/k3po/nukleus/ext/internal/behavior/layout/StreamsLayout.java
> +                CloseHelper.close(createEmptyFile(streams, streamsSize + throttleSize));
Excellent, this is a much better fix!

2017-05-09 17:08 UTC, jfallows approved these changes

2017-05-09 17:08 UTC, merged